// List of FIPS-compliant plugins as of 2023-02-01
def fipsPlugins = ['ace-editor','analysis-model-api','ant','antisamy-markup-formatter','apache-httpcomponents-client-4-api','async-http-client','aws-credentials','aws-java-sdk','blueocean-commons','bootstrap4-api','bouncycastle-api','branch-api','caffeine-api','checks-api','cloudbees-administrative-monitors','cloudbees-analytics','cloudbees-assurance','cloudbees-blueocean-default-theme','cloudbees-casc-api','cloudbees-casc-server','cloudbees-folder','cloudbees-folders-plus','cloudbees-github-reporting','cloudbees-groovy-view','cloudbees-ha','cloudbees-jenkins-advisor','cloudbees-jsync-archiver','cloudbees-license','cloudbees-monitoring','cloudbees-nodes-plus','cloudbees-pipeline-policies','cloudbees-platform-common','cloudbees-platform-data','cloudbees-plugin-usage','cloudbees-request-filter','cloudbees-servicenow-jenkins-plugin','cloudbees-ssh-slaves','cloudbees-support','cloudbees-template','cloudbees-uc-data-api','cloudbees-unified-ui','cloudbees-update-center-plugin','cloudbees-view-creation-filter','cloudbees-workflow-template','cloudbees-workflow-ui','command-launcher','configuration-as-code','credentials','credentials-binding','data-tables-api','display-url-api','durable-task','echarts-api','email-ext','external-monitor-job','external-notification','fips-file-data-gathering','font-awesome-api','forensics-api','git','git-client','github','github-api','github-branch-source','git-server','gradle','handlebars','handy-uri-templates-2-api','infradna-backup','jackson2-api','javadoc','jaxb','jdk-tool','jjwt-api','jquery3-api','jquery-detached','jsch','junit','ldap','mailer','mapdb-api','matrix-auth','matrix-project','maven-plugin','metrics','momentjs','nectar-license','nectar-rbac','node-iterator-api','notification-api','okhttp-api','operations-center-agent','operations-center-client','operations-center-cloud','operations-center-clusterops','operations-center-context','operations-center-jnlp-controller','operations-center-license','operations-center-monitoring','operations-center-notification','operations-center-rbac','operations-center-server','operations-center-sso','operations-center-updatecenter','pam-auth','pipeline-build-step','pipeline-event-step','pipeline-graph-analysis','pipeline-input-step','pipeline-milestone-step','pipeline-model-api','pipeline-model-definition','pipeline-model-extensions','pipeline-rest-api','pipeline-stage-step','pipeline-stage-tags-metadata','pipeline-stage-view','plain-credentials','plugin-util-api','popper-api','scm-api','script-security','snakeyaml-api','ssh-credentials','structs','support-core','suppress-stack-trace','timestamper','token-macro','trilead-api','user-activity-monitoring','variant','Windows-slaves','workflow-aggregator','workflow-api','workflow-basic-steps','workflow-cps','workflow-cps-checkpoint','workflow-cps-global-lib','workflow-durable-task-step','workflow-job','workflow-multibranch','workflow-scm-step','workflow-step-api','workflow-support']

// Collect a list of all installed plugins on this controller
def plugins = jenkins.model.Jenkins.instance.getPluginManager().getPlugins()
plugins.each {
  // If installed plugin is not in the FIPS-compliant list, print out the name and version
  if (!fipsPlugins.contains(it.getShortName())) {
	  println "${it.getShortName()}: ${it.getVersion()}"
  }
}
return null
